language: objective-c
osx_image: xcode8.2
sudo: false

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install && cd $TRAVIS_BUILD_DIR

script: 
- xctool -workspace RainReminder.xcworkspace -scheme RainReminder -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' ONLY_ACTIVE_ARCH=NO; 
